name: Build and Deploy Angular App to Azure App Service

on:
  push:
    branches:
      - main  # Cambia esto por el nombre de tu rama principal si es diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: |
        # Personalizar el comando de instalación
        npm install --force

    - name: Build Angular App
      run: |
        # Cambia la configuración si es necesario (por ejemplo, si usas una configuración específica de entorno)
        npm run build

    - name: Deploy to Azure App Service
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_SMOKE_01525B710 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "/" # App source code path
        api_location: "" # Api source code path - optional
        output_location: "dist/" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######
